servers:
  Chaos:
    map_image: "../svrMaps/Chaos-classic-20260224.png"
    map_size_tiles: 2048
    server_mode: "pvp"
    supports_kingdoms: true
    guard_tower_influence_radius_tiles: 50
    scales: [0.55, 0.60, 0.65, 0.70, 0.75, 0.80, 0.85, 0.90]

    blur_ksize: 11
    canny1: 40
    canny2: 130

    score_weights:
      edges: 0.81
      gray: 0.19

    avoid_water: true
    water_hsv_lo: [85, 20, 20]
    water_hsv_hi: [140, 255, 255]

    hint_use_roi: true
    hint_soft_bias: true
    hint_bias_sigma: 0.55
    hint_bias_min_weight: 0.25

    topk: 20

  Xanadu:
    map_image: "../svrMaps/Xanadu-classic-20260224.png"
    map_size_tiles: 8192
    server_mode: "pve"
    supports_kingdoms: false
    scales: [0.55, 0.60, 0.65, 0.70, 0.75, 0.80, 0.85, 0.90]

    blur_ksize: 11
    canny1: 40
    canny2: 130

    score_weights:
      edges: 0.81
      gray: 0.19

    avoid_water: true
    water_hsv_lo: [85, 20, 20]
    water_hsv_hi: [140, 255, 255]

    hint_use_roi: true
    hint_soft_bias: true
    hint_bias_sigma: 0.55
    hint_bias_min_weight: 0.25

    topk: 20